# Adjustment


start_time="2021-01-01"

end_time="2021-12-31"

Daily Arithmetic Mean may change

In [2]:
import pandas as pd
import numpy as np

In [4]:
df_p = pd.read_csv('c/part-00000-f6d12335-bd1c-4f64-8e51-7c3d1ec94ae7-c000.csv')

In [5]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1241290 entries, 0 to 1241289
Data columns (total 31 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   Latitude             1241290 non-null  float64
 1   Longitude            1241290 non-null  float64
 2   POC                  1241290 non-null  int64
 3   Event Type           1241290 non-null  object
 4   count                1241290 non-null  int64
 5   State Code           1241290 non-null  int64
 6   County Code          1241290 non-null  int64
 7   Site Num             1241290 non-null  int64
 8   Parameter Code       1241290 non-null  int64
 9   Datum                1241290 non-null  object
 10  Parameter Name       1241290 non-null  object
 11  Sample Duration      1241290 non-null  object
 12  Pollutant Standard   1241290 non-null  object
 13  Date Local           1241290 non-null  object
 14  Units of Measure     1241290 non-null  object
 15  Observation Count    1241290 non-null  int64
 16  Observation Percent  1241290 non-null  float64
 17  Arithmetic Mean      1241290 non-null  float64
 18  1st Max Value        1241290 non-null  float64
 19  1st Max Hour         1241290 non-null  int64
 20  AQI                  620611 non-null   float64
 21  Method Code          620679 non-null   float64
 22  Method Name          1241290 non-null  object
 23  Local Site Name      1230773 non-null  object
 24  Address              1241290 non-null  object
 25  State Name           1241290 non-null  object
 26  County Name          1241290 non-null  object
 27  City Name            1241290 non-null  object
 28  CBSA Name            1220058 non-null  object
 29  Date of Last Change  1241290 non-null  object
 30  point_num            1241290 non-null  int64
dtypes: float64(7), int64(9), object(15)
memory usage: 293.6+ MB

In [14]:
Coordinates_p = pd.read_csv('cord.csv')

In [7]:
num = len(Coordinates)
num

276

In [8]:
pd.set_option('display.max_columns',None)
df_p.head(5)

,Latitude,Longitude,POC,Event Type,count,State Code,County Code,Site Num,Parameter Code,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change,point_num
0,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2015-01-01T00:00:00.000-05:00,Parts per million,23,96.0,0.189739,0.213,0,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2021-11-08T00:00:00.000-05:00,1
1,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2021-01-01T00:00:00.000-05:00,Parts per million,23,96.0,0.235087,0.262,18,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2022-03-14T00:00:00.000-04:00,1
2,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2015-01-02T00:00:00.000-05:00,Parts per million,23,96.0,0.216130,0.343,23,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2021-11-08T00:00:00.000-05:00,1
3,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2021-01-02T00:00:00.000-05:00,Parts per million,23,96.0,0.204130,0.232,21,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2022-03-14T00:00:00.000-04:00,1
4,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2015-01-03T00:00:00.000-05:00,Parts per million,23,96.0,0.337783,0.377,9,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2021-11-08T00:00:00.000-05:00,1

In [9]:
df_p['Date Local'].str[0:10]

0          2015-01-01
1          2021-01-01
2          2015-01-02
3          2021-01-02
4          2015-01-03
              ...
1241285    2016-12-27
1241286    2016-12-28
1241287    2016-12-29
1241288    2016-12-30
1241289    2016-12-31
Name: Date Local, Length: 1241290, dtype: object

In [10]:
df_p['Date Local standard'] = df_p['Date Local'].str[0:10]

In [11]:
df_p.head(5)

,Latitude,Longitude,POC,Event Type,count,State Code,County Code,Site Num,Parameter Code,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change,point_num,Date Local standard
0,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2015-01-01T00:00:00.000-05:00,Parts per million,23,96.0,0.189739,0.213,0,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2021-11-08T00:00:00.000-05:00,1,2015-01-01
1,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2021-01-01T00:00:00.000-05:00,Parts per million,23,96.0,0.235087,0.262,18,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2022-03-14T00:00:00.000-04:00,1,2021-01-01
2,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2015-01-02T00:00:00.000-05:00,Parts per million,23,96.0,0.216130,0.343,23,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2021-11-08T00:00:00.000-05:00,1,2015-01-02
3,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2021-01-02T00:00:00.000-05:00,Parts per million,23,96.0,0.204130,0.232,21,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2022-03-14T00:00:00.000-04:00,1,2021-01-02
4,43.46611,-88.62111,1,None,5072,55,27,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2015-01-03T00:00:00.000-05:00,Parts per million,23,96.0,0.337783,0.377,9,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,HORICON WILDLIFE AREA,"Horicon Wildlife Area, 1210 N Palmatory St",Wisconsin,Dodge,Kekoskee,"Beaver Dam, WI",2021-11-08T00:00:00.000-05:00,1,2015-01-03

In [19]:
df_p[(df_p['City Name'] == "Pittsburgh") & (df_p['Date Local standard'] == '2015-05-05')]

,Latitude,Longitude,POC,Event Type,count,State Code,County Code,Site Num,Parameter Code,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change,point_num,Date Local standard
515898,40.465420,-79.960757,2,None,4770,42,3,8,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2015-05-05T00:00:00.000-04:00,Parts per million,23,96.0,0.255739,0.372,7,NaN,593.0,INSTRUMENTAL - Gas Filter Correlation Teledyne...,Lawrenceville,"301 39th St, Pittsburgh, PA 15201 (Lawrenceville)",Pennsylvania,Allegheny,Pittsburgh,"Pittsburgh, PA",2021-11-08T00:00:00.000-05:00,117,2015-05-05
516346,40.465420,-79.960757,2,None,4770,42,3,8,42101,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,CO 8-hour 1971,2015-05-05T00:00:00.000-04:00,Parts per million,24,100.0,0.237500,0.300,7,3.0,NaN,-,Lawrenceville,"301 39th St, Pittsburgh, PA 15201 (Lawrenceville)",Pennsylvania,Allegheny,Pittsburgh,"Pittsburgh, PA",2021-11-08T00:00:00.000-05:00,117,2015-05-05
819195,40.443367,-79.990293,1,None,4189,42,3,31,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2015-05-05T00:00:00.000-04:00,Parts per million,23,96.0,0.352174,0.700,20,NaN,93.0,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,Flag Plaza,"1275 Bedford Ave, Pittsburgh, PA 15219 (Flag P...",Pennsylvania,Allegheny,Pittsburgh,"Pittsburgh, PA",2021-11-08T00:00:00.000-05:00,183,2015-05-05
819925,40.443367,-79.990293,1,None,4189,42,3,31,42101,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,CO 8-hour 1971,2015-05-05T00:00:00.000-04:00,Parts per million,24,100.0,0.300000,0.500,23,6.0,NaN,-,Flag Plaza,"1275 Bedford Ave, Pittsburgh, PA 15219 (Flag P...",Pennsylvania,Allegheny,Pittsburgh,"Pittsburgh, PA",2021-11-08T00:00:00.000-05:00,183,2015-05-05

# CO Data

In [15]:
start_time="2015-01-01"

end_time="2021-12-31"

# days should be 2257

pdates = pd.date_range(start=start_time, end=end_time)

em = []

Coordinates = Coordinates_p.to_numpy()

Values = []

for i in range(1,num+1,1):
    
    #df_sub_p = df_p[df_p["point_num"] == i].set_index("Date Local")
    
    #df_sub_p_resampled = df_sub_p.resample("D").mean()
    
    #df_sub_p_365 = df_sub_p_resampled.fillna(df_sub_p_resampled.mean())
    
    #z = df_sub_p_365.iloc[:,9].to_numpy()# Daily Arithmetic Mean
    
    df_sub_p = df_p[df_p["point_num"] == i].set_index("Date Local standard")
    
    if (True in df_sub_p.index.duplicated()):
        print("df_sub_p duplicated index, point num is",i)
        em.append(i)
    else:

        df_sub_p_reindex = df_sub_p.reindex(pdates,fill_value=None)

        df_sub_p_365 = df_sub_p_reindex.fillna(df_sub_p_reindex.mean())

        #z = df_sub_p_365.iloc[:,17].to_numpy()# Daily Arithmetic Mean
        z = df_sub_p_365['Arithmetic Mean'].to_numpy()# Daily Arithmetic Mean

        if len(z)==2557:
            Values.append(z)
        else:
            print("Not 2557, point num is",i)
    
Values = np.array(Values)

df_sub_p duplicated index, point num is 1
df_sub_p duplicated index, point num is 2
df_sub_p duplicated index, point num is 3
df_sub_p duplicated index, point num is 4
df_sub_p duplicated index, point num is 5
df_sub_p duplicated index, point num is 6
df_sub_p duplicated index, point num is 7
df_sub_p duplicated index, point num is 8
df_sub_p duplicated index, point num is 9
df_sub_p duplicated index, point num is 10
df_sub_p duplicated index, point num is 11
df_sub_p duplicated index, point num is 12
df_sub_p duplicated index, point num is 13
df_sub_p duplicated index, point num is 14
df_sub_p duplicated index, point num is 15
df_sub_p duplicated index, point num is 16
df_sub_p duplicated index, point num is 17
df_sub_p duplicated index, point num is 18
df_sub_p duplicated index, point num is 19
df_sub_p duplicated index, point num is 20
df_sub_p duplicated index, point num is 21
df_sub_p duplicated index, point num is 22
df_sub_p duplicated index, point num is 23
df_sub_p duplicated index, point num is 24
df_sub_p duplicated index, point num is 25
df_sub_p duplicated index, point num is 26
df_sub_p duplicated index, point num is 27
df_sub_p duplicated index, point num is 28
df_sub_p duplicated index, point num is 29
df_sub_p duplicated index, point num is 30
df_sub_p duplicated index, point num is 31
df_sub_p duplicated index, point num is 32
df_sub_p duplicated index, point num is 33
df_sub_p duplicated index, point num is 34
df_sub_p duplicated index, point num is 35
df_sub_p duplicated index, point num is 36
df_sub_p duplicated index, point num is 37
df_sub_p duplicated index, point num is 38
df_sub_p duplicated index, point num is 39
df_sub_p duplicated index, point num is 40
df_sub_p duplicated index, point num is 41
df_sub_p duplicated index, point num is 42
df_sub_p duplicated index, point num is 43
df_sub_p duplicated index, point num is 44
df_sub_p duplicated index, point num is 45
df_sub_p duplicated index, point num is 46
df_sub_p duplicated index, point num is 47
df_sub_p duplicated index, point num is 48
df_sub_p duplicated index, point num is 49
df_sub_p duplicated index, point num is 50
df_sub_p duplicated index, point num is 51
df_sub_p duplicated index, point num is 52
df_sub_p duplicated index, point num is 53
df_sub_p duplicated index, point num is 54
df_sub_p duplicated index, point num is 55
df_sub_p duplicated index, point num is 56
df_sub_p duplicated index, point num is 57
df_sub_p duplicated index, point num is 58
df_sub_p duplicated index, point num is 59
df_sub_p duplicated index, point num is 60
df_sub_p duplicated index, point num is 61
df_sub_p duplicated index, point num is 62
df_sub_p duplicated index, point num is 63
df_sub_p duplicated index, point num is 64
df_sub_p duplicated index, point num is 65
df_sub_p duplicated index, point num is 66
df_sub_p duplicated index, point num is 67
df_sub_p duplicated index, point num is 68
df_sub_p duplicated index, point num is 69
df_sub_p duplicated index, point num is 70
df_sub_p duplicated index, point num is 71
df_sub_p duplicated index, point num is 72
df_sub_p duplicated index, point num is 73
df_sub_p duplicated index, point num is 74
df_sub_p duplicated index, point num is 75
df_sub_p duplicated index, point num is 76
df_sub_p duplicated index, point num is 77
df_sub_p duplicated index, point num is 78
df_sub_p duplicated index, point num is 79
df_sub_p duplicated index, point num is 80
df_sub_p duplicated index, point num is 81
df_sub_p duplicated index, point num is 82
df_sub_p duplicated index, point num is 83
df_sub_p duplicated index, point num is 84
df_sub_p duplicated index, point num is 85
df_sub_p duplicated index, point num is 86
df_sub_p duplicated index, point num is 87
df_sub_p duplicated index, point num is 88
df_sub_p duplicated index, point num is 89
df_sub_p duplicated index, point num is 90
df_sub_p duplicated index, point num is 91
df_sub_p duplicated index, point num is 92
df_sub_p duplicated index, point num is 93
df_sub_p duplicated index, point num is 94
df_sub_p duplicated index, point num is 95
df_sub_p duplicated index, point num is 96
df_sub_p duplicated index, point num is 97
df_sub_p duplicated index, point num is 98
df_sub_p duplicated index, point num is 99
df_sub_p duplicated index, point num is 100
df_sub_p duplicated index, point num is 101
df_sub_p duplicated index, point num is 102
df_sub_p duplicated index, point num is 103
df_sub_p duplicated index, point num is 104
df_sub_p duplicated index, point num is 105
df_sub_p duplicated index, point num is 106
df_sub_p duplicated index, point num is 107
df_sub_p duplicated index, point num is 108
df_sub_p duplicated index, point num is 109
df_sub_p duplicated index, point num is 110
df_sub_p duplicated index, point num is 111
df_sub_p duplicated index, point num is 112
df_sub_p duplicated index, point num is 113
df_sub_p duplicated index, point num is 114
df_sub_p duplicated index, point num is 115
df_sub_p duplicated index, point num is 116
df_sub_p duplicated index, point num is 117
df_sub_p duplicated index, point num is 118
df_sub_p duplicated index, point num is 119
df_sub_p duplicated index, point num is 120
df_sub_p duplicated index, point num is 121
df_sub_p duplicated index, point num is 122
df_sub_p duplicated index, point num is 123
df_sub_p duplicated index, point num is 124
df_sub_p duplicated index, point num is 125
df_sub_p duplicated index, point num is 126
df_sub_p duplicated index, point num is 127
df_sub_p duplicated index, point num is 128
df_sub_p duplicated index, point num is 129
df_sub_p duplicated index, point num is 130
df_sub_p duplicated index, point num is 131
df_sub_p duplicated index, point num is 132
df_sub_p duplicated index, point num is 133
df_sub_p duplicated index, point num is 134
df_sub_p duplicated index, point num is 135
df_sub_p duplicated index, point num is 136
df_sub_p duplicated index, point num is 137
df_sub_p duplicated index, point num is 138
df_sub_p duplicated index, point num is 139
df_sub_p duplicated index, point num is 140
df_sub_p duplicated index, point num is 141
df_sub_p duplicated index, point num is 142
df_sub_p duplicated index, point num is 143
df_sub_p duplicated index, point num is 144
df_sub_p duplicated index, point num is 145
df_sub_p duplicated index, point num is 146
df_sub_p duplicated index, point num is 147
df_sub_p duplicated index, point num is 148
df_sub_p duplicated index, point num is 149
df_sub_p duplicated index, point num is 150
df_sub_p duplicated index, point num is 151
df_sub_p duplicated index, point num is 152
df_sub_p duplicated index, point num is 153
df_sub_p duplicated index, point num is 154
df_sub_p duplicated index, point num is 155
df_sub_p duplicated index, point num is 156
df_sub_p duplicated index, point num is 157
df_sub_p duplicated index, point num is 158
df_sub_p duplicated index, point num is 159
df_sub_p duplicated index, point num is 160
df_sub_p duplicated index, point num is 161
df_sub_p duplicated index, point num is 162
df_sub_p duplicated index, point num is 163
df_sub_p duplicated index, point num is 164
df_sub_p duplicated index, point num is 165
df_sub_p duplicated index, point num is 166
df_sub_p duplicated index, point num is 167
df_sub_p duplicated index, point num is 168
df_sub_p duplicated index, point num is 169
df_sub_p duplicated index, point num is 170
df_sub_p duplicated index, point num is 171
df_sub_p duplicated index, point num is 172
df_sub_p duplicated index, point num is 173
df_sub_p duplicated index, point num is 174
df_sub_p duplicated index, point num is 175
df_sub_p duplicated index, point num is 176
df_sub_p duplicated index, point num is 177
df_sub_p duplicated index, point num is 178
df_sub_p duplicated index, point num is 179
df_sub_p duplicated index, point num is 180
df_sub_p duplicated index, point num is 181
df_sub_p duplicated index, point num is 182
df_sub_p duplicated index, point num is 183
df_sub_p duplicated index, point num is 184
df_sub_p duplicated index, point num is 185
df_sub_p duplicated index, point num is 186
df_sub_p duplicated index, point num is 187
df_sub_p duplicated index, point num is 188
df_sub_p duplicated index, point num is 189
df_sub_p duplicated index, point num is 190
df_sub_p duplicated index, point num is 191
df_sub_p duplicated index, point num is 192
df_sub_p duplicated index, point num is 193
df_sub_p duplicated index, point num is 194
df_sub_p duplicated index, point num is 195
df_sub_p duplicated index, point num is 196
df_sub_p duplicated index, point num is 197
df_sub_p duplicated index, point num is 198
df_sub_p duplicated index, point num is 199
df_sub_p duplicated index, point num is 200
df_sub_p duplicated index, point num is 201
df_sub_p duplicated index, point num is 202
df_sub_p duplicated index, point num is 203
df_sub_p duplicated index, point num is 204
df_sub_p duplicated index, point num is 205
df_sub_p duplicated index, point num is 206
df_sub_p duplicated index, point num is 207
df_sub_p duplicated index, point num is 208
df_sub_p duplicated index, point num is 209
df_sub_p duplicated index, point num is 210
df_sub_p duplicated index, point num is 211
df_sub_p duplicated index, point num is 212
df_sub_p duplicated index, point num is 213
df_sub_p duplicated index, point num is 214
df_sub_p duplicated index, point num is 215
df_sub_p duplicated index, point num is 216
df_sub_p duplicated index, point num is 217
df_sub_p duplicated index, point num is 218
df_sub_p duplicated index, point num is 219
df_sub_p duplicated index, point num is 220
df_sub_p duplicated index, point num is 221
df_sub_p duplicated index, point num is 222
df_sub_p duplicated index, point num is 223
df_sub_p duplicated index, point num is 224
df_sub_p duplicated index, point num is 225
df_sub_p duplicated index, point num is 226
df_sub_p duplicated index, point num is 227
df_sub_p duplicated index, point num is 228
df_sub_p duplicated index, point num is 229
df_sub_p duplicated index, point num is 230
df_sub_p duplicated index, point num is 231
df_sub_p duplicated index, point num is 232
df_sub_p duplicated index, point num is 233
df_sub_p duplicated index, point num is 234
df_sub_p duplicated index, point num is 235
df_sub_p duplicated index, point num is 236
df_sub_p duplicated index, point num is 237
df_sub_p duplicated index, point num is 238
df_sub_p duplicated index, point num is 239
df_sub_p duplicated index, point num is 240
df_sub_p duplicated index, point num is 241
df_sub_p duplicated index, point num is 242
df_sub_p duplicated index, point num is 243
df_sub_p duplicated index, point num is 244
df_sub_p duplicated index, point num is 245
df_sub_p duplicated index, point num is 246
df_sub_p duplicated index, point num is 247
df_sub_p duplicated index, point num is 248
df_sub_p duplicated index, point num is 249
df_sub_p duplicated index, point num is 250
df_sub_p duplicated index, point num is 251
df_sub_p duplicated index, point num is 252
df_sub_p duplicated index, point num is 253
df_sub_p duplicated index, point num is 254
df_sub_p duplicated index, point num is 255
df_sub_p duplicated index, point num is 256
df_sub_p duplicated index, point num is 257
df_sub_p duplicated index, point num is 258
df_sub_p duplicated index, point num is 259
df_sub_p duplicated index, point num is 260
df_sub_p duplicated index, point num is 261
df_sub_p duplicated index, point num is 262
df_sub_p duplicated index, point num is 263
df_sub_p duplicated index, point num is 264
df_sub_p duplicated index, point num is 265
df_sub_p duplicated index, point num is 266
df_sub_p duplicated index, point num is 267
df_sub_p duplicated index, point num is 268
df_sub_p duplicated index, point num is 269
df_sub_p duplicated index, point num is 270
df_sub_p duplicated index, point num is 271
df_sub_p duplicated index, point num is 272
df_sub_p duplicated index, point num is 273
df_sub_p duplicated index, point num is 274
df_sub_p duplicated index, point num is 275
df_sub_p duplicated index, point num is 276

In [16]:
df_sub_p

,Latitude,Longitude,POC,Event Type,count,State Code,County Code,Site Num,Parameter Code,Datum,Parameter Name,Sample Duration,Pollutant Standard,Date Local,Units of Measure,Observation Count,Observation Percent,Arithmetic Mean,1st Max Value,1st Max Hour,AQI,Method Code,Method Name,Local Site Name,Address,State Name,County Name,City Name,CBSA Name,Date of Last Change,point_num
Date Local standard,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2019-01-01,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2019-01-01T00:00:00.000-05:00,Parts per million,23,96.0,0.330435,0.6,20,NaN,54.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-01T00:00:00.000-04:00,276
2017-01-01,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2017-01-01T00:00:00.000-05:00,Parts per million,23,96.0,0.469565,0.7,20,NaN,54.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-05T00:00:00.000-04:00,276
2019-01-02,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2019-01-02T00:00:00.000-05:00,Parts per million,23,96.0,0.478261,1.0,7,NaN,54.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-01T00:00:00.000-04:00,276
2017-01-02,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2017-01-02T00:00:00.000-05:00,Parts per million,23,96.0,0.473913,0.7,0,NaN,54.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-05T00:00:00.000-04:00,276
2019-01-03,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,1 HOUR,CO 1-hour 1971,2019-01-03T00:00:00.000-05:00,Parts per million,23,96.0,0.495652,1.0,8,NaN,54.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-01T00:00:00.000-04:00,276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-27,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,CO 8-hour 1971,2016-12-27T00:00:00.000-05:00,Parts per million,24,100.0,0.708333,0.9,0,10.0,NaN,-,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-08T00:00:00.000-05:00,276
2016-12-28,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,CO 8-hour 1971,2016-12-28T00:00:00.000-05:00,Parts per million,24,100.0,0.700000,0.8,0,9.0,NaN,-,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-08T00:00:00.000-05:00,276
2016-12-29,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,CO 8-hour 1971,2016-12-29T00:00:00.000-05:00,Parts per million,24,100.0,0.695833,0.9,0,10.0,NaN,-,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-08T00:00:00.000-05:00,276
2016-12-30,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,CO 8-hour 1971,2016-12-30T00:00:00.000-05:00,Parts per million,24,100.0,0.754167,1.0,0,11.0,NaN,-,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-08T00:00:00.000-05:00,276
2016-12-31,37.97231,-122.520004,1,None,5089,6,41,1,42101,WGS84,Carbon monoxide,8-HR RUN AVG END HOUR,CO 8-hour 1971,2016-12-31T00:00:00.000-05:00,Parts per million,24,100.0,0.487500,0.6,21,7.0,NaN,-,San Rafael,534 4TH ST.,California,Marin,San Rafael,"San Francisco-Oakland-Hayward, CA",2021-11-08T00:00:00.000-05:00,276

In [17]:
df_sub_p_reindex

NameError: name 'df_sub_p_reindex' is not defined

In [88]:
Coordinates.shape

(626, 2)

In [89]:
Values.shape

(626, 2557)

In [96]:
Values[3]

array([nan, nan, nan, ..., nan, nan, nan])

# Coordinate Data for Pitts 

[40.46542,-79.960757]

In [75]:
np.where(Coordinates==40.46542)

(array([575]), array([0]))

In [76]:
Coordinates[575]

array([ 40.46542 , -79.960757])

# X and Y for model

In [77]:
x=np.zeros((num-1,2557,3))
cord=np.delete(Coordinates,575,axis=0)-Coordinates[575]
valu=np.delete(Values,575,axis=0)

for m in range(num-1):
    for n in range(2557):
        x[m,n,0]=cord[m,0]
        x[m,n,1]=cord[m,1]
        x[m,n,2]=valu[m,0]

In [81]:
valu[1]

array([nan, nan, nan, ..., nan, nan, nan])

In [78]:
x.shape

(625, 2557, 3)

In [80]:
x[1,1,]

array([ -4.632694, -13.247503,        nan])

In [ ]:
y = Values.reshape()